# Generated by Django 5.1.1 on 2024-09-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_number', models.IntegerField(default=0)),
                ('address_street', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=200)),
                ('parcel_id', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('zoning', models.CharField(max_length=200)),
                ('sale_date', models.CharField(max_length=200)),
                ('sale_price', models.CharField(max_length=200)),
                ('legal_reference', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('assessment_year', models.CharField(max_length=200)),
                ('land_area', models.CharField(max_length=200)),
                ('building_value', models.CharField(max_length=200)),
                ('extra_features_value', models.CharField(max_length=200)),
                ('land_value', models.CharField(max_length=200)),
                ('total_value', models.CharField(max_length=200)),
                ('narrative_description', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
